# Generated by Django 4.2.9 on 2024-02-03 13:06

import core.models
from django.db import migrations
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20231023_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveresult',
            name='id',
        ),
        migrations.AlterField(
            model_name='archiveresult',
            name='uuid',
            field=core.models.UUIDAutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='snapshot',
            name='id',
            field=core.models.UUIDAutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
